networks:
  motorway-backend-network:
    name: "motorway-backend-network"
    driver: "bridge"
services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway-v1
    ports:
      - 5432:5432
    networks:
      - motorway-backend-network

  redistimeseries:
    container_name: redislabs-redistimeseries
    image: redislabs/redistimeseries:latest
    ports:
      - 6379:6379
    networks:
      - motorway-backend-network

  app:
    depends_on:
      - "db"
      - "redistimeseries"
    container_name: app
    build: ./
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - PG_URL=postgres://user:password@db:5432/motorway-v1
      - REDIS_URL=redis://redistimeseries
      - LOG_DIR=log
    networks:
      - motorway-backend-network